---
title: "Forecasting: Independent Study"
---

Repo for independent study on forecasting following Hyndman & Athanasopoulos

# Resources

- A web variant of the book can be found here: https://otexts.org/fpp2/
- A print variant can be found here: https://www.amazon.com/dp/0987507117?tag=otexts-20
- `fable` package: https://github.com/tidyverts/fable
- Course materials with slides: https://github.com/robjhyndman/ETC3550Slides
- `fpp2` package: http://pkg.robjhyndman.com/fpp2-package/
- Rob Hyndman video: https://www.youtube.com/watch?v=yx6OQ-8HofU

# Description

> Typical statistics for scientists and engineers require an assumption that all data is independent and identically distributed (iid).  This course introduces a comprehensive introduction to statistical methods for time-series data, where our data is very much not independent, but highly correlated.  Topics that will be included involve time series regression models, time series decomposition, exponential smoothening, autoregressive integrated moving average models (ARIMA), and hierarchical models.
